version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ../app:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/z-custom.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www
    environment:
      XDEBUG_MODE: develop,debug
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
      - redis  # Dependência opcional
      - rabbitmq  # Dependência opcional
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    volumes:
      - ../app:/var/www
    working_dir: /var/www
    command: php artisan horizon
    depends_on:
      - app
      - redis
    networks:
      - laravel
    restart: unless-stopped
  db:
    image: mysql:8.4
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ../app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:management
    container_name: laravel-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # Porta AMQP
      - "15672:15672"  # Porta do Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - laravel

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  laravel: